name: Update Extensions

on:
  # Enable manual trigger
  workflow_dispatch:
  # Trigger every day
  schedule:
    - cron: "0 0 * * *"
  push:

env:
  nixpkgs: nixpkgs=https://github.com/NixOS/nixpkgs/archive/cd87aef066e4bdbb1139845500072bd252d37c5e.tar.gz
  extra_nix_config: |
    substituters = https://cache.nixos.org https://nix-community.cachix.org https://fog.cachix.org
    trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= fog.cachix.org-1:FAxiA6qMLoXEUdEq+HaT24g1MjnxdfygrbrLDBp6U/s=

jobs:
  update-extensions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}\nsubstituters = https://cache.nixos.org/ https://cache.iog.io https://nix-community.cachix.org https://deemp.cachix.org \ntrusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= haskell-language-server.cachix.org-1:juFfHrwkOxqIOZShtC4YC1uT1bBcq2RSvC7OMKx0Nz8= deemp.cachix.org-1:9shDxyR2ANqEPQEEYDL/xIOnoPwxHot21L5fiZnFL18=\nstore = /home/runner/nix\n"
          install_url: https://releases.nixos.org/nix/nix-2.14.1/install
      - name: Restore and cache Nix store
        uses: actions/cache@v3.3.0
        with:
          key: ${{ runner.os }}-nix-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
          path: /home/runner/nix
          restore-keys: |
            ${{ runner.os }}-nix-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
            ${{ runner.os }}-nix-
      - name: Run updater
        uses: nick-fields/retry@v2
        env:
          CONFIG: "hs/config.yaml"
        with:
          timeout_minutes: 360
          retry_wait_seconds: 300
          max_attempts: 6
          command: nix run nix-dev/#updateExtensions

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "action: update extensions"
          git push
